version: "3.9"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8080"   # 3001 es el puerto externo (en tu VPS), 8080 el interno (en el contenedor)
    restart: always

